// header file generated by txt2h, Original in 2003-2006 by ScottManDeath
//Modified by Marcos Alcoforado
#ifndef  TXT_HEADER_Color2D_VS
#define  TXT_HEADER_Color2D_VS
const char *Color2D_VS={
"attribute vec2 a_vertex;\n"
"attribute vec4 a_color;\n"
"varying vec4 f_color;\n"
"void main(void)\n"
"{\n"
"    gl_Position = vec4(a_vertex,0,1);\n"
"    f_color = a_color;\n"
"}\n"
"\n"
};
#endif  // #ifdef TXT_HEADER_Color2D_VS
