// header file generated by txt2h, Original in 2003-2006 by ScottManDeath
Modified by Marcos Alcoforado
#ifndef  TXT_HEADER_Color2D
#define  TXT_HEADER_Color2D
char Color2D[]=
"varying vec4 f_color;\n"
"\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_FragColor = f_color;\n"
"}\n"
"\n"
#endif  // #ifdef TXT_HEADER_Color2D
